import { Product } from "./store";

export const categories = [
  { name: "Vibradores", slug: "vibradores", description: "Tecnologia e design a serviço do prazer feminino e compartilhado.", image: "https://nivelsecreto.com.br/wp-content/uploads/elementor/thumbs/ifonnx-toys-Id_jzYP7h6s-unsplash-scaled-r5rmkehsv1eqy6wnec8j0w2z09hdgxkae4opo2lnpg.jpg" },
  { name: "Masturbadores", slug: "masturbadores", description: "Engenharia de precisão para o prazer masculino.", image: "https://nivelsecreto.com.br/wp-content/uploads/elementor/thumbs/lovense-toys-BttrI8hxmi8-unsplash-scaled-r5rmghi0dw1qkolg9nahmvntwgsbec0juqtvokepms.jpg" },
  { name: "Plug Anal", slug: "plug-anal", description: "Exploração gradual com conforto e materiais de excelência.", image: "https://nivelsecreto.com.br/wp-content/uploads/elementor/thumbs/gwen-mamanoleas-ZwKAJ0zmk6Y-unsplash-scaled-r5rluv7n72gbjjzyiaveac261fcecy6svqnubggoqs.jpg" },
  { name: "Fetiche & Sado", slug: "fetiche-e-sado", description: "Confiança, poder e entrega em materiais premium.", image: "https://nivelsecreto.com.br/wp-content/uploads/elementor/thumbs/pexels-31299941-8587249-r5rlpa26kisyj0454vx8gqtiwyvulq08s31xm8qxqc.jpg" },
  { name: "Acessórios", slug: "acessorios", description: "Complementos essenciais para elevar cada momento.", image: "https://nivelsecreto.com.br/wp-content/uploads/elementor/thumbs/andrey-matveev-WydWcF2EPjc-unsplash-scaled-r5rls7c3tyt2nbv825fg8095g4gyjtm6ik4bd8eudg.jpg" },
  { name: "Próteses", slug: "proteses", description: "Realismo e qualidade em silicone médico certificado.", image: "https://nivelsecreto.com.br/wp-content/uploads/elementor/thumbs/gwen-mamanoleas-N2ZsTxVBIN4-unsplash-1-scaled-r5rlkrg3q6mcqgocifmrzdus5b5cm32ohq6xldg1ms.jpg" },
];

export const products: Product[] = [
  {
    id: "1",
    name: "Vibrador Duplo Motor 15cm",
    slug: "vibrador-jelly-duplo-motor-15cm",
    description: "Motor duplo para estimulação simultânea interna e externa. Material flexível body-safe, design ergonômico. 15cm de comprimento útil.",
    price: 64.99,
    originalPrice: 79.99,
    images: ["https://nivelsecreto.com.br/wp-content/uploads/2025/05/20859-4-300x300.jpg"],
    category: "Vibradores",
    categorySlug: "vibradores",
    badge: "Promoção",
    inStock: true,
  },
  {
    id: "2",
    name: "Massageador Wand Recarregável 10V",
    slug: "varinha-magica-36cm-recarregavel",
    description: "Massageador de alta potência com 10 padrões de vibração. Recarregável via USB, silicone hipoalergênico premium. 36cm.",
    price: 109.90,
    originalPrice: 129.99,
    images: ["https://nivelsecreto.com.br/wp-content/uploads/2025/05/3018-4-300x300.jpg"],
    category: "Vibradores",
    categorySlug: "vibradores",
    badge: "Destaque",
    inStock: true,
  },
  {
    id: "3",
    name: "Masturbador Discreto com Vibração",
    slug: "vagina-lanterna-vibracao",
    description: "Design compacto e discreto com motor de vibração multivelocidade. Material cyberskin de toque ultra realista.",
    price: 109.99,
    originalPrice: 149.50,
    images: ["https://nivelsecreto.com.br/wp-content/uploads/2025/05/17724-4-300x300.jpg"],
    category: "Masturbadores",
    categorySlug: "masturbadores",
    badge: "Promoção",
    inStock: true,
  },
  {
    id: "4",
    name: "Vibrador para Casais — Controle Remoto",
    slug: "vibrador-casal-longa-distancia",
    description: "Controle via aplicativo a qualquer distância. Bluetooth, à prova d'água, silicone médico certificado. Projetado para uso a dois.",
    price: 399.80,
    originalPrice: 450.00,
    images: ["https://nivelsecreto.com.br/wp-content/uploads/2025/05/18877-4-300x300.jpg"],
    category: "Vibradores",
    categorySlug: "vibradores",
    badge: "Premium",
    inStock: true,
  },
  {
    id: "5",
    name: "Kit Plug Anal em Silicone — 3 Peças",
    slug: "plug-anal-silicone-kit-3",
    description: "Três tamanhos progressivos em silicone médico. Base de segurança alargada, superfície acetinada para máximo conforto.",
    price: 89.90,
    originalPrice: 119.90,
    images: ["/products/plug-1.jpg"],
    category: "Plug Anal",
    categorySlug: "plug-anal",
    badge: "Kit",
    inStock: true,
  },
  {
    id: "6",
    name: "Kit Bondage Premium — 7 Peças",
    slug: "kit-bondage-luxo-7-pecas",
    description: "Conjunto completo em couro sintético de alta qualidade. Inclui restrições, venda e acessórios complementares.",
    price: 199.90,
    originalPrice: 259.90,
    images: ["/products/fetiche-1.jpg"],
    category: "Fetiche & Sado",
    categorySlug: "fetiche-e-sado",
    badge: "Kit Completo",
    inStock: true,
  },
  {
    id: "7",
    name: "Óleo de Massagem Sensorial",
    slug: "oleo-massagem-sensual",
    description: "Óleo com efeito aquecedor gradual para massagens. Fragrância sutil, textura sedosa, não mancha tecidos.",
    price: 39.90,
    images: ["/products/acessorio-1.jpg"],
    category: "Acessórios",
    categorySlug: "acessorios",
    inStock: true,
  },
  {
    id: "8",
    name: "Prótese Realística 18cm com Ventosa",
    slug: "protese-realistica-18cm-ventosa",
    description: "Acabamento hiper-realístico com texturas detalhadas. Ventosa de fixação resistente, silicone premium flexível e body-safe.",
    price: 129.90,
    originalPrice: 159.90,
    images: ["/products/protese-1.jpg"],
    category: "Próteses",
    categorySlug: "proteses",
    inStock: true,
  },
  {
    id: "9",
    name: "Anel Vibratório Recarregável para Casais",
    slug: "anel-peniano-vibratorio",
    description: "Silicone elástico com 10 modos de vibração. Estimulação simultânea para ambos, recarregável via USB.",
    price: 79.90,
    originalPrice: 99.90,
    images: ["/products/acessorio-2.jpg"],
    category: "Acessórios",
    categorySlug: "acessorios",
    badge: "Para Casais",
    inStock: true,
  },
  {
    id: "10",
    name: "Estimulador de Pressão — 7 Intensidades",
    slug: "sugador-clitoris-7-intensidades",
    description: "Tecnologia de ondas de pressão com 7 níveis de intensidade. Silicone ultra macio, à prova d'água, recarregável via USB.",
    price: 189.90,
    originalPrice: 239.90,
    images: ["/products/vibrador-2.jpg"],
    category: "Vibradores",
    categorySlug: "vibradores",
    badge: "Tendência",
    inStock: true,
  },
  {
    id: "11",
    name: "Masturbador Automático Rotativo",
    slug: "masturbador-automatico-rotativo",
    description: "Movimentos rotativos e de sucção automáticos com 7 modos. Recarregável, material TPE premium de toque realista.",
    price: 299.90,
    originalPrice: 379.90,
    images: ["/products/masturbador-2.jpg"],
    category: "Masturbadores",
    categorySlug: "masturbadores",
    badge: "Tecnologia",
    inStock: true,
  },
  {
    id: "12",
    name: "Chicote Artesanal em Couro",
    slug: "chicote-couro-artesanal",
    description: "Confecção artesanal em couro legítimo com cabo ergonômico. Tiras macias que permitem intensidades variadas.",
    price: 89.90,
    images: ["/products/fetiche-2.jpg"],
    category: "Fetiche & Sado",
    categorySlug: "fetiche-e-sado",
    inStock: true,
  },
];

export function getProductsByCategory(categorySlug: string): Product[] {
  return products.filter((p) => p.categorySlug === categorySlug);
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.badge);
}

export function getBestSellers(): Product[] {
  return products.slice(0, 4);
}
